name: HACS Action
uses: hacs/action@22.5.0

on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 * * *"



  jobs:
    validate-hacs:
      runs-on: "ubuntu-latest"
      name: With HACS Action
      steps:
         - name: ✅ HACS validation
           uses: "hacs/action@main"
           with:
             category: "template"
