name: HACS Action
uses: hacs/action@22.5.0

on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 * * *"



  jobs:
  validate-hassfest:
    runs-on: "ubuntu-latest"
    name: With hassfest
    steps:
      - name: ✅ Hassfest validation
        uses: "home-assistant/actions/hassfest@master"

 validate-hacs:
    runs-on: "ubuntu-latest"
    name: With HACS Action
    steps:
      - name: ✅ HACS validation
        uses: "hacs/action@main"
        with:
          category: "integration"
